// SB Burger Week 2026 — Restaurant Data
// Event: February 19–25, 2026
// Source: Santa Barbara Independent
const SOURCE_URL = "https://www.independent.com/2026/02/05/burger-week-2026/";

const AREA_COLORS = {
  "Downtown SB": "#e63946",
  "Goleta": "#2d6a4f",
  "Carpinteria": "#1d3557",
  "Isla Vista": "#7b2cbf",
  "Santa Ynez": "#e76f51",
  "Other SB": "#e07a5f"
};

const restaurants = [
  // --- Downtown SB ---
  {
    name: "Arnoldi's",
    address: "600 Olive St., Santa Barbara, CA",
    website: "https://www.arnoldis.com/",
    phone: "805-962-5394",
    area: "Downtown SB",
    lat: 34.423278, 
    lng: -119.691155,
    mapUrl: "https://maps.app.goo.gl/UUefNcGFbYjGUNPd7",
    appleMapsUrl: "https://maps.apple/p/U3gWeWbcVqKjsb",
    burger: "the burger",
    description: "more details"
  },
  {
    name: "Downtown Eats",
    address: "634 State St., Santa Barbara, CA",
    website: "https://www.yelp.com/biz/downtown-eats-santa-barbara",
    phone: "805-453-9796",
    area: "Downtown SB",
    lat: 34.418771, 
    lng: -119.697599,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=634+State+St+Santa+Barbara+CA",
    appleMapsUrl: "https://maps.apple/p/CH80ruBx0tokCj",
    burger: null,
    description: null
  },
  {
    name: "Dom's Taverna",
    address: "30 E. Victoria St., Santa Barbara, CA",
    website: "https://www.domstaverna.com/",
    phone: "805-724-4338",
    area: "Downtown SB",
    lat: 34.424864, 
    lng: -119.704726,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=30+E+Victoria+St+Santa+Barbara+CA",
    appleMapsUrl: "https://maps.apple/p/xvK6mAKKw55U4p",
    burger: null,
    description: null
  },
  {
    name: "Eureka!",
    address: "601 Paseo Nuevo, Santa Barbara, CA",
    website: "https://eurekarestaurantgroup.com/locations/santa-barbara",
    phone: "805-618-3388",
    area: "Downtown SB",
    lat: 34.418597, 
    lng: -119.700307,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=601+Paseo+Nuevo+Santa+Barbara+CA",
    appleMapsUrl: "https://maps.apple/p/o6XV_nkn5Yobot",
    burger: null,
    description: null
  },
  {
    name: "Finch and Fork",
    address: "31 W. Carrillo St., Santa Barbara, CA",
    website: "https://www.finchandforkrestaurant.com/",
    phone: "805-879-9100",
    area: "Downtown SB",
    lat: 34.420427, 
    lng: -119.702788,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=31+W+Carrillo+St+Santa+Barbara+CA",
    appleMapsUrl: "https://maps.apple/p/P6GFr7sFA.Xmp-",
    burger: null,
    description: null
  },
  {
    name: "Fresco At The Market",
    address: "38 W. Victoria St. Ste. 102, Santa Barbara, CA",
    website: "https://www.fresco-sb.com/",
    phone: "805-770-7994",
    area: "Downtown SB",
    lat: 34.423601, 
    lng: -119.707027,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=38+W+Victoria+St+Santa+Barbara+CA",
    appleMapsUrl: "https://maps.apple/p/9pZqFtJLsFJMmn",
    burger: null,
    description: null
  },
  {
    name: "Gala",
    address: "705 Anacapa St., Santa Barbara, CA",
    website: "https://www.galasb.com/",
    phone: "805-869-2813",
    area: "Downtown SB",
    lat: 34.419770, 
    lng: -119.697264,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=705+Anacapa+St+Santa+Barbara+CA",
    appleMapsUrl: "https://maps.apple/p/hFLAzvWWQkJEUn",
    burger: null,
    description: null
  },
  {
    name: "Goat Tree",
    address: "36 State St., Santa Barbara, CA",
    website: "https://www.hotelcalifornian.com/goat-tree.htm",
    phone: "805-882-0137",
    area: "Downtown SB",
    lat: 34.413505, 
    lng: -119.690624,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=36+State+St+Santa+Barbara+CA",
    appleMapsUrl: "https://maps.apple/p/PcPGZE_I~qS5LH",
    burger: null,
    description: null
  },
  {
    name: "Little Bird Kitchen",
    address: "38 W. Victoria St., Santa Barbara, CA",
    website: "littlebirdsb.com",
    phone: "805-303-7865",
    area: "Downtown SB",
    lat: 34.423532, 
    lng: -119.706990,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=38+W+Victoria+St+Santa+Barbara+CA",
    appleMapsUrl: "https://maps.apple/p/mC3RDF86ZgNghN",
    burger: null,
    description: null
  },
  {
    name: "Pascucci",
    address: "1230-A State St., Santa Barbara, CA",
    website: "pascuccirestaurant-sb.com",
    phone: "805-963-8123",
    area: "Downtown SB",
    lat: 34.424304, 
    lng: -119.705252,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=1230+State+St+Santa+Barbara+CA",
    appleMapsUrl: "https://maps.apple/p/.acg2UBX9RIsmD",
    burger: null,
    description: null
  },
  {
    name: "Poke House",
    address: "811 State St. Ste. D, Santa Barbara, CA",
    website: "https://www.poke.house/",
    phone: "805-869-2722",
    area: "Downtown SB",
    lat: 34.419647, 
    lng: -119.700116,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=811+State+St+Santa+Barbara+CA",
    appleMapsUrl: "https://maps.apple/p/prDjK9G_-rFP.K",
    burger: null,
    description: null
  },
  {
    name: "Que Smoke Shack",
    address: "38 W. Victoria St., Santa Barbara, CA",
    website: "quesmokeshack.com",
    phone: "805-869-2193",
    area: "Downtown SB",
    lat: 34.423601, 
    lng: -119.707027,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=38+W+Victoria+St+Santa+Barbara+CA",
    appleMapsUrl: "https://maps.apple/p/ocM85RZ2z3h26k",
    burger: null,
    description: null
  },
  {
    name: "SB Biergarten",
    address: "11 Anacapa St., Santa Barbara, CA",
    website: "beersantabarbara.com",
    phone: "805-856-6694",
    area: "Downtown SB",
    lat: 34.413321, 
    lng: -119.688943,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=11+Anacapa+St+Santa+Barbara+CA",
    appleMapsUrl: "https://maps.apple/p/dUKud0Wn3XcgJw",
    burger: null,
    description: null
  },
  {
    name: "The Brewhouse",
    address: "229 W Montecito St., Santa Barbara, CA",
    website: "sbbrewhouse.com",
    phone: "805-884-4664",
    area: "Downtown SB",
    lat: 34.411938, 
    lng: -119.695913,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=229+W+Montecito+St+Santa+Barbara+CA",
    appleMapsUrl: "https://maps.apple/p/Ua9iRD~BAuQ5s.z",
    burger: null,
    description: null
  },
  {
    name: "Seoulmate Kitchen",
    address: "38 W. Victoria St. Ste. 115, Santa Barbara, CA",
    website: "seoulmatekitchen.com",
    phone: "805-869-2566",
    area: "Downtown SB",
    lat: 34.423601, 
    lng: -119.707027,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=38+W+Victoria+St+Santa+Barbara+CA",
    appleMapsUrl: "https://maps.apple/p/IAXTbR~k-gkNIa",
    burger: null,
    description: null
  },
  {
    name: "Shalhoob's Funk Zone Patio",
    address: "220 Gray Ave., Santa Barbara, CA",
    website: "shalhoob.com",
    phone: "+1 (805) 963-7733",
    area: "Downtown SB",
    lat: 34.416328, 
    lng: -119.690533,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=220+Gray+Ave+Santa+Barbara+CA",
    appleMapsUrl: "https://maps.apple/p/y~H7PBSHU37cZZ",
    burger: null,
    description: null
  },
  {
    name: "The Blue Owl",
    address: "5 W. Canon Perdido, Santa Barbara, CA",
    website: "theblueowlsb.com",
    phone: "+1 (805) 705-0991",
    area: "Downtown SB",
    lat: 34.420052, 
    lng: -119.700900,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=5+W+Canon+Perdido+Santa+Barbara+CA",
    appleMapsUrl: "https://maps.apple/p/afaRbEdoeqivz_",
    burger: null,
    description: null
  },
  {
    name: "The Win-dow",
    address: "701 Chapala St., Santa Barbara, CA",
    website: "",
    phone: "",
    area: "Downtown SB",
    lat: 34.4177,
    lng: -119.6997,
    mapUrl: "https://maps.app.goo.gl/umr83npQPfSKA8AM8",
    appleMapsUrl: "https://maps.apple/p/pDBVZsfDszCyIQ",
    burger: null,
    description: null
  },
  {
    name: "Third Window Brewing (Santa Barbara)",
    address: "406 E. Haley St. Ste #3, Santa Barbara, CA",
    website: "",
    phone: "",
    area: "Downtown SB",
    lat: 34.4174,
    lng: -119.6920,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=406+E+Haley+St+Santa+Barbara+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  },
  {
    name: "Validation Ale (Downtown)",
    address: "102 E. Yanonali St., Santa Barbara, CA",
    website: "",
    phone: "",
    area: "Downtown SB",
    lat: 34.4150,
    lng: -119.6902,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=102+E+Yanonali+St+Santa+Barbara+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  },
  {
    name: "Crush Cakes (Santa Barbara)",
    address: "1315 Anacapa St., Santa Barbara, CA",
    website: "",
    phone: "",
    area: "Downtown SB",
    lat: 34.4257,
    lng: -119.7053,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=1315+Anacapa+St+Santa+Barbara+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  },

  // --- Other SB ---
  {
    name: "Corner Tap",
    address: "1905 Cliff Dr., Santa Barbara, CA",
    website: "",
    phone: "",
    area: "Other SB",
    lat: 34.4013,
    lng: -119.7224,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=1905+Cliff+Dr+Santa+Barbara+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  },
  {
    name: "Dave's Dogs",
    address: "149 S Turnpike Rd., Santa Barbara, CA",
    website: "",
    phone: "",
    area: "Other SB",
    lat: 34.4378,
    lng: -119.7897,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=149+S+Turnpike+Rd+Santa+Barbara+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  },
  {
    name: "Islands",
    address: "3825 State St. Space E-149, Santa Barbara, CA",
    website: "",
    phone: "",
    area: "Other SB",
    lat: 34.4480,
    lng: -119.7340,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=3825+State+St+Santa+Barbara+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  },
  {
    name: "Mesa Burger",
    address: "315 Meigs Rd., Santa Barbara, CA",
    website: "",
    phone: "",
    area: "Other SB",
    lat: 34.4006,
    lng: -119.7225,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=315+Meigs+Rd+Santa+Barbara+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  },
  {
    name: "Sama San Roque",
    address: "3435 State St., Santa Barbara, CA",
    website: "",
    phone: "",
    area: "Other SB",
    lat: 34.4403,
    lng: -119.7382,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=3435+State+St+Santa+Barbara+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  },
  {
    name: "The Patio Cafe",
    address: "3007 De La Vina St., Santa Barbara, CA",
    website: "",
    phone: "",
    area: "Other SB",
    lat: 34.4388,
    lng: -119.7289,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=3007+De+La+Vina+St+Santa+Barbara+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  },
  {
    name: "Validation Ale (De La Vina)",
    address: "2840 De La Vina St., Santa Barbara, CA",
    website: "",
    phone: "",
    area: "Other SB",
    lat: 34.4375,
    lng: -119.7261,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=2840+De+La+Vina+St+Santa+Barbara+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  },
  {
    name: "Yellow Belly Tap",
    address: "2611 De La Vina St., Santa Barbara, CA",
    website: "",
    phone: "",
    area: "Other SB",
    lat: 34.4349,
    lng: -119.7247,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=2611+De+La+Vina+St+Santa+Barbara+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  },

  // --- Goleta ---
  {
    name: "Caya",
    address: "5650 Calle Real, Goleta, CA",
    website: "",
    phone: "",
    area: "Goleta",
    lat: 34.4419,
    lng: -119.8210,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=5650+Calle+Real+Goleta+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  },
  {
    name: "Cristino's Bakery",
    address: "170 Aero Camino, Goleta, CA",
    website: "",
    phone: "",
    area: "Goleta",
    lat: 34.4323,
    lng: -119.8480,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=170+Aero+Camino+Goleta+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  },
  {
    name: "Crush Cakes (Goleta)",
    address: "5392 Hollister Ave., Goleta, CA",
    website: "",
    phone: "",
    area: "Goleta",
    lat: 34.4354,
    lng: -119.8123,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=5392+Hollister+Ave+Goleta+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  },
  {
    name: "Home Plate",
    address: "7398 Calle Real #C, Goleta, CA",
    website: "",
    phone: "",
    area: "Goleta",
    lat: 34.4336,
    lng: -119.8848,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=7398+Calle+Real+Goleta+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  },
  {
    name: "Jonesy's Fried Chicken",
    address: "282 Orange Ave., Goleta, CA",
    website: "",
    phone: "",
    area: "Goleta",
    lat: 34.4342,
    lng: -119.8286,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=282+Orange+Ave+Goleta+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  },
  {
    name: "Kyle's Kitchen (Hollister)",
    address: "7000 Hollister Ave., Goleta, CA",
    website: "",
    phone: "",
    area: "Goleta",
    lat: 34.4305,
    lng: -119.8724,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=7000+Hollister+Ave+Goleta+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  },
  {
    name: "Kyle's Kitchen (Calle Real)",
    address: "5723 Calle Real, Goleta, CA",
    website: "",
    phone: "",
    area: "Goleta",
    lat: 34.4409,
    lng: -119.8241,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=5723+Calle+Real+Goleta+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  },
  {
    name: "Rinkside Cafe",
    address: "6985 Santa Felicia Dr., Goleta, CA",
    website: "",
    phone: "",
    area: "Goleta",
    lat: 34.4258,
    lng: -119.8712,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=6985+Santa+Felicia+Dr+Goleta+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  },
  {
    name: "SB Fish Market",
    address: "7127 Hollister Ave. Ste. 18, Goleta, CA",
    website: "",
    phone: "",
    area: "Goleta",
    lat: 34.4305,
    lng: -119.8750,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=7127+Hollister+Ave+Goleta+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  },
  {
    name: "Shalhoob (Goleta)",
    address: "5112 Hollister Ave., Goleta, CA",
    website: "",
    phone: "",
    area: "Goleta",
    lat: 34.4303,
    lng: -119.8060,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=5112+Hollister+Ave+Goleta+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  },
  {
    name: "The Nugget (Goleta)",
    address: "5687 Calle Real, Goleta, CA",
    website: "",
    phone: "",
    area: "Goleta",
    lat: 34.4408,
    lng: -119.8230,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=5687+Calle+Real+Goleta+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  },
  {
    name: "White Caps Beach Club",
    address: "6775 Hollister Ave., Goleta, CA",
    website: "",
    phone: "",
    area: "Goleta",
    lat: 34.4287,
    lng: -119.8652,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=6775+Hollister+Ave+Goleta+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  },

  // --- Carpinteria ---
  {
    name: "Dang Burger",
    address: "5080 A Carpinteria Ave., Carpinteria, CA",
    website: "",
    phone: "",
    area: "Carpinteria",
    lat: 34.3985,
    lng: -119.5200,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=5080+Carpinteria+Ave+Carpinteria+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  },
  {
    name: "Padaro Beach Grill",
    address: "3765 Santa Claus Lane, Carpinteria, CA",
    website: "",
    phone: "",
    area: "Carpinteria",
    lat: 34.4066,
    lng: -119.5483,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=3765+Santa+Claus+Lane+Carpinteria+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  },
  {
    name: "The Nugget (Summerland)",
    address: "2318 Lillie Ave., Summerland, CA",
    website: "",
    phone: "",
    area: "Carpinteria",
    lat: 34.4217,
    lng: -119.5995,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=2318+Lillie+Ave+Summerland+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  },
  {
    name: "The Nugget (Carpinteria)",
    address: "892 Linden Ave., Carpinteria, CA",
    website: "",
    phone: "",
    area: "Carpinteria",
    lat: 34.3981,
    lng: -119.5192,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=892+Linden+Ave+Carpinteria+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  },
  {
    name: "Third Window Brewing (Carpinteria)",
    address: "720 Linden Ave., Carpinteria, CA",
    website: "",
    phone: "",
    area: "Carpinteria",
    lat: 34.3971,
    lng: -119.5204,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=720+Linden+Ave+Carpinteria+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  },

  // --- Isla Vista ---
  {
    name: "IV Deli Mart",
    address: "6553 Pardall Rd., Isla Vista, CA",
    website: "",
    phone: "",
    area: "Isla Vista",
    lat: 34.4129,
    lng: -119.8564,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=6553+Pardall+Rd+Isla+Vista+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  },

  // --- Santa Ynez ---
  {
    name: "The Victor",
    address: "3631 Sagunto St., Santa Ynez, CA",
    website: "",
    phone: "",
    area: "Santa Ynez",
    lat: 34.6129,
    lng: -120.0789,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=3631+Sagunto+St+Santa+Ynez+CA",
    appleMapsUrl: null,
    burger: null,
    description: null
  }
];
