// trending.js — auto-generated by GitHub Action, do not edit manually
const TRENDING = {
  "Arnoldi's": {
    "views": 267,
    "intents": 27
  },
  "Validation Ale": {
    "views": 213,
    "intents": 20
  },
  "Goat Tree": {
    "views": 220,
    "intents": 16
  },
  "SB Biergarten": {
    "views": 209,
    "intents": 14
  },
  "Gala": {
    "views": 239,
    "intents": 14
  },
  "White Caps Beach Club": {
    "views": 305,
    "intents": 13
  },
  "Seoulmate Kitchen": {
    "views": 123,
    "intents": 13
  },
  "Yellow Belly Tap": {
    "views": 313,
    "intents": 13
  },
  "Dom's Taverna": {
    "views": 274,
    "intents": 12
  },
  "Mesa Burger": {
    "views": 167,
    "intents": 11
  },
  "The Nugget (Goleta)": {
    "views": 209,
    "intents": 11
  },
  "All": {
    "views": 0,
    "intents": 11
  },
  "Third Window Brewing (Santa Barbara)": {
    "views": 272,
    "intents": 10
  },
  "Dave's Dogs Grill": {
    "views": 223,
    "intents": 10
  },
  "glutenFree": {
    "views": 0,
    "intents": 10
  },
  "Pascucci": {
    "views": 312,
    "intents": 10
  },
  "Finch and Fork": {
    "views": 296,
    "intents": 10
  },
  "Downtown Eats": {
    "views": 283,
    "intents": 10
  },
  "Sama San Roque": {
    "views": 277,
    "intents": 9
  },
  "Dang Burger": {
    "views": 118,
    "intents": 9
  },
  "Cristino's Bakery": {
    "views": 291,
    "intents": 8
  },
  "The Victor": {
    "views": 192,
    "intents": 8
  },
  "Jonesy's Fried Chicken": {
    "views": 325,
    "intents": 8
  },
  "Santa Barbara Fish Market": {
    "views": 277,
    "intents": 8
  },
  "Shalhoob's (Magnolia)": {
    "views": 278,
    "intents": 8
  },
  "Rinkside Cafe": {
    "views": 261,
    "intents": 7
  },
  "The Blue Owl": {
    "views": 268,
    "intents": 7
  },
  "vegan": {
    "views": 0,
    "intents": 7
  },
  "The Win-dow": {
    "views": 304,
    "intents": 7
  },
  "Caya": {
    "views": 266,
    "intents": 7
  },
  "hasFries": {
    "views": 0,
    "intents": 6
  },
  "Little Bird Kitchen": {
    "views": 233,
    "intents": 6
  },
  "Home Plate Grill": {
    "views": 239,
    "intents": 6
  },
  "Que Smoke Shack": {
    "views": 130,
    "intents": 6
  },
  "Eureka!": {
    "views": 216,
    "intents": 6
  },
  "Corner Tap": {
    "views": 125,
    "intents": 6
  },
  "Islands Fine Burgers & Drinks": {
    "views": 290,
    "intents": 6
  },
  "The Patio Cafe": {
    "views": 270,
    "intents": 5
  },
  "Downtown SB": {
    "views": 0,
    "intents": 5
  },
  "Shalhoob's Funk Zone Patio": {
    "views": 215,
    "intents": 5
  },
  "Validation Annex": {
    "views": 11,
    "intents": 4
  },
  "Crushcakes": {
    "views": 182,
    "intents": 4
  },
  "IV Deli Mart": {
    "views": 142,
    "intents": 4
  },
  "Poke House": {
    "views": 212,
    "intents": 3
  },
  "The Nugget (Carpinteria)": {
    "views": 107,
    "intents": 3
  },
  "Kyle's Kitchen (Calle Real)": {
    "views": 162,
    "intents": 3
  },
  "Crushcakes and Cafe": {
    "views": 259,
    "intents": 3
  },
  "Padaro Beach Grill": {
    "views": 85,
    "intents": 1
  },
  "Goleta": {
    "views": 0,
    "intents": 1
  },
  "vegetarian": {
    "views": 0,
    "intents": 1
  },
  "Other SB": {
    "views": 0,
    "intents": 1
  },
  "Santa Ynez": {
    "views": 0,
    "intents": 1
  },
  "The Brewhouse": {
    "views": 196,
    "intents": 1
  },
  "Kyle's Kitchen (Hollister)": {
    "views": 203,
    "intents": 1
  },
  "Fresco At The Market": {
    "views": 99,
    "intents": 0
  },
  "The Nugget (Summerland)": {
    "views": 121,
    "intents": 0
  },
  "Third Window Brewing (Carpinteria)": {
    "views": 122,
    "intents": 0
  }
};
